package dkg

import (
	"crypto/rand"
	"fmt"
	"math/big"
	"reliable/utils/crypto"
)

// polynomial represents a polynomial over Z_q.
// Coefficients[0] is the free term (a₀), Coefficients[t] is the leading coefficient.
type polynomial struct {
	coefficients []*crypto.ZpElement
	q            *big.Int
}

// polynomialPair holds the two polynomials generated by a participant in DKG Phase 1.
// F is the secret polynomial, FPrime is the masking polynomial for Pedersen commitments.
type polynomialPair struct {
	f     *polynomial
	fMask *polynomial
}

// generatePolynomials creates a pair of random polynomials of degree t over Z_q.
// t — threshold (degree of polynomials), meaning t+1 participants needed for reconstruction.
// The free term a₀ of F is the participant's secret contribution to the shared key.
// The free term b₀ of FPrime is the masking value for the Pedersen commitment to a₀.
func generatePolynomials(params *crypto.Params, t int) (*polynomialPair, error) {
	if t < 0 {
		return nil, fmt.Errorf("polynomial degree t must be non-negative, got %d", t)
	}

	f, err := randomPolynomial(params.Q, t)
	if err != nil {
		return nil, fmt.Errorf("failed to generate secret polynomial f: %w", err)
	}

	fPrime, err := randomPolynomial(params.Q, t)
	if err != nil {
		return nil, fmt.Errorf("failed to generate masking polynomial f': %w", err)
	}

	return &polynomialPair{f: f, fMask: fPrime}, nil
}

// randomPolynomial generates a random polynomial of given degree with coefficients in Z_q.
// All coefficients are uniformly random from [0, q-1].
func randomPolynomial(q *big.Int, degree int) (*polynomial, error) {
	coeffs := make([]*crypto.ZpElement, degree+1)

	for i := 0; i <= degree; i++ {
		val, err := rand.Int(rand.Reader, q)
		if err != nil {
			return nil, fmt.Errorf("failed to generate random coefficient [%d]: %w", i, err)
		}
		coeffs[i] = crypto.NewZpElement(val, q)
	}

	return &polynomial{coefficients: coeffs, q: q}, nil
}

// Evaluate computes f(x) mod q using Horner's method.
// x is given as int (participant index, 1-based).
func (p *polynomial) Evaluate(x int) *crypto.ZpElement {
	xElem := crypto.NewZpElement(big.NewInt(int64(x)), p.q)

	// Horner's method: result = c[t]; for k = t-1..0: result = result*x + c[k]
	degree := len(p.coefficients) - 1
	result := p.coefficients[degree].Clone()

	for k := degree - 1; k >= 0; k-- {
		result = result.Mul(xElem)
		result = result.Add(p.coefficients[k])
	}

	return result
}

// Degree returns the degree of the polynomial.
func (p *polynomial) Degree() int {
	return len(p.coefficients) - 1
}

// FreeTerm returns the free term (a₀) — the secret contribution of the participant.
func (p *polynomial) FreeTerm() *crypto.ZpElement {
	return p.coefficients[0]
}
